id: P005610
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14517
  title: བསླབ་སྟོན་གནད་ཀྱི་སྒྲོན་མེ།
  author: ''
  volumes:
    d7c65c4633a54feaa5ac57a2bfad856f:
      image_group_id: I1KG18525
      title: ''
      volume_number: 1
      total_pages: 490
      base_file: v001.txt
