id: P005610
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14517
  title: བསླབ་སྟོན་གནད་ཀྱི་སྒྲོན་མེ།
  author: ''
  volumes:
    d7c65c4633a54feaa5ac57a2bfad856f:
      image_group_id: I1KG18525
      title: ''
      volume_number: 1
      total_pages: 490
